### ISSUE TITLE
buck: command not found

### ISSUE THREAD

**Issue by p1v0t** [LoopPerfect/buckaroo#183]
## Description
I installed **buckaroo** with debian package, and try to quickstart tutorial from documentation site but when I want to run `buck run :main` I get `buck: command not found` from terminal (bash). 
I search for buck with `apt-cache search buck` but doesn't find such a package.

## Steps to Reproduce

1. Install the **buckaroo** from [here](https://github.com/LoopPerfect/buckaroo/releases)
2. install it with `dpkg -i buckaroo.deb`
3. `buckaroo update`
4. Try quickstart tutorial

## Context

It doesn't affect me at all but make somewhat disappoint, when I try a new tool, I want to see it working on the first project.

## Your Environment

* Version used: 1.5.0
* Operating System and Architecture: Debian 9 amd64

Thank you kindly all :smile:

**Comment by abranhe** [comment]
@p1v0t Your problem is not with **buckaroo** itself, it is with [buck](https://github.com/facebook/buck), You will need to install buck first since buckaroo is based on it. [Read the buck documentation](https://buckbuild.com/setup/getting_started.html) for the installation instructions on Linux/Debian. 

After you have buck installed on your computer you will be able to use

```
buck run :main
```

To check if you have buck installed, make sure you run the quickstart tutorial and **run inside the project**

```
buck --help
```

Make sure you are running buck inside a project containing a `.buckconfig` file, since buck as November 2018 isn't supporting buck commands outside the project directory. See [buck Issue #2050](https://github.com/facebook/buck/issues/2050).

---

@njlr I think we will need to include to the documentation the steps needed to install buck on other operating systems different than macOS.

**Comment by p1v0t** [comment]
Thank you for this rapid feedback. I installed the `buck` and it's working now :+1: :smile:

**Comment by njlr** [comment]
Awesome ❤️
