### ISSUE TITLE
Installation via homebrew (macos Sierra) fails

### ISSUE THREAD

**Issue by onionhammer** [LoopPerfect/buckaroo#54]
```
MacBook-Pro-3:buckaroo myuser$ brew install --HEAD loopperfect/lp/buckaroo

==> Installing buckaroo from loopperfect/lp
==> Cloning git@github.com:loopperfect/buckaroo.git
Cloning into '/Users/myuser/Library/Caches/Homebrew/buckaroo--git'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failed to download resource "buckaroo"
Failure while executing: git clone --branch master git@github.com:loopperfect/buckaroo.git /Users/myuser/Library/Caches/Homebrew/buckaroo--git
```

**Comment by njlr** [comment]
This issue occurs when you try to install a Homebrew formula with an SSH Git URL but [have not configured SSH Git before](https://help.github.com/articles/error-permission-denied-publickey/). 

Since others might run into the same problem, I have updated our Homebrew formula so that it uses an HTTPS Git URL instead. 

Would you mind trying again now?

**Comment by onionhammer** [comment]
@njlr I had actually already resolved this myself shortly after posting, so I can't really easily re-test it

**Comment by njlr** [comment]
OK, glad to hear it's working. I'll close out this issue.
