### ISSUE TITLE
v0.1.2 Update command throws NullPointerException

### ISSUE THREAD

**Issue by voldyman** [LoopPerfect/buckaroo#79]
The `UpdateCommand` class returns null from the `routine()` method where it should return `IO.println("Not Implemented yet!")`

Due to this there is a null pointer exception which is not helpful.

to reproduce this error add the following test to v1.1.2

```
  @Test
    public void testUpdateParserNiy() throws Exception {
        final CLICommand updateCommand = CLIParsers.commandParser.parse("update");
        updateCommand.routine().run(IOContext.fake());
        assertTrue("Should Reach here", true);
    }
```

**Comment by njlr** [comment]
Do you mean `v0.1.2`? `v1.1.2` doesn't exist yet!

**Comment by voldyman** [comment]
oops, typo :)

**Comment by njlr** [comment]
In `v0.1.2` the `update` command is indeed not working. It is also [not documented](http://buckaroo.readthedocs.io/en/latest/cli.html#). 

The idea behind `update` was to provide a way for the user to update the dependencies installed in their project after the cookbook has been updated. With the current commands, this is equivalent to:  

```bash=
# Remove the buckaroo folder from your project directory
rm -rf ./buckaroo/

# Run install again
buckaroo install
```

This should be [fixed in v1.2.0](https://github.com/LoopPerfect/buckaroo/blob/release/0.1.2/src/main/java/com/loopperfect/buckaroo/cli/UpgradeCommand.java), which resolves dependencies slightly differently to `v0.1.*`.  

@nikhedonia should we patch `v0.1.2`?

**Comment by njlr** [comment]
If you want to fetch the latest version of the cookbook, the command is: 

```bash=
buckaroo upgrade
```

**Comment by voldyman** [comment]
Yup, figured that out but a lot of command's routine method still return null in v 0.1.2.

Feel free to mark it won't fix if you want to, I got this version because homebrew provided v0.1.2

**Comment by njlr** [comment]
Now that `v1.2.0` I think we can mark this as `won't fix`. 

The [documentation](https://buckaroo.readthedocs.io/en/latest/cli.html#update) for `upgrade` and `update` has been updated.
